<a href="https://colab.research.google.com/github/Yanina2105/Heart-attack_project/blob/develop/Limpieza_de_datos_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Exploración del dataset**

## **Cargar librerias y revisión básica**

In [ ]:
from pathlib import Path

import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
DATA_PATH = Path('/content/drive/MyDrive/Proyecto_de_tesis/datos_2020/data')
PROCESSED_DATA_PATH = DATA_PATH / 'processed'

FINAL_FILE_WITH_NANS_PATH = PROCESSED_DATA_PATH / 'heart_with_nans_2020.csv'

In [ ]:
heart_2020_df = pd.read_csv(FINAL_FILE_WITH_NANS_PATH)

/tmp/ipython-input-2172687843.py:1: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  heart_2020_df = pd.read_csv(FINAL_FILE_WITH_NANS_PATH)

In [ ]:
heart_2020_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401958 entries, 0 to 401957
Data columns (total 36 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   State                      401958 non-null  object
 1   Sex                        401958 non-null  object
 2   GeneralHealth              400997 non-null  object
 3   PhysicalHealthDays         393267 non-null  float64
 4   MentalHealthDays           394029 non-null  float64
 5   LastCheckupTime            394851 non-null  object
 6   PhysicalActivities         401276 non-null  object
 7   SleepHours                 397264 non-null  float64
 8   RemovedTeeth               392161 non-null  object
 9   HadHeartAttack             399875 non-null  object
 10  HadAngina                  398656 non-null  object
 11  HadStroke                  400772 non-null  object
 12  HadAsthma                  400591 non-null  object
 13  HadSkinCancer              400683 non-null  object
 14  TypeOfCancer               8987 non-null    object
 15  HadCOPD                    400003 non-null  object
 16  HadDepressiveDisorder      399655 non-null  object
 17  HadKidneyDisease           399855 non-null  object
 18  HadArthritis               400442 non-null  object
 19  HadDiabetes                401144 non-null  object
 20  DifficultyWalking          385199 non-null  object
 21  DifficultyDressingBathing  385364 non-null  object
 22  DifficultyErrands          383849 non-null  object
 23  SmokerStatus               380858 non-null  object
 24  ECigaretteUsage            50666 non-null   object
 25  RaceEthnicityCategory      392970 non-null  object
 26  AgeCategory                393701 non-null  object
 27  HeightInMeters             380227 non-null  float64
 28  WeightInKilograms          367010 non-null  float64
 29  BMI                        360601 non-null  float64
 30  AlcoholDrinkers            375183 non-null  object
 31  HIVTesting                 349091 non-null  object
 32  FluVaxLast12               376216 non-null  object
 33  PneumoVaxEver              345526 non-null  object
 34  CancerSurvivor             400775 non-null  object
 35  Year                       401958 non-null  int64
dtypes: float64(6), int64(1), object(29)
memory usage: 110.4+ MB

In [ ]:
heart_2020_df.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,AgeCategory,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,CancerSurvivor,Year
0,Alabama,Female,Very good,3.0,30.0,5 or more years ago,Yes,5.0,"6 or more, but not all",No,...,Age 55 to 59,1.70,48.08,16.60,No,Yes,No,No,Yes,2020
1,Alabama,Female,Good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,1 to 5,No,...,Age 65 to 69,1.63,77.11,29.18,NaN,NaN,NaN,NaN,No,2020
2,Alabama,Female,Good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,NaN,No,...,Age 65 to 69,1.73,NaN,NaN,No,No,Yes,No,Yes,2020
3,Alabama,Female,Excellent,0.0,0.0,Within past 2 years (1 year but less than 2 ye...,No,6.0,1 to 5,No,...,Age 80 or older,NaN,NaN,NaN,No,No,No,No,No,2020
4,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,None of them,No,...,Age 80 or older,1.68,57.15,20.34,No,NaN,Yes,Yes,No,2020

## **Estadísticas y valores únicos**

In [ ]:
heart_2020_df.describe(include='all')

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,AgeCategory,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,CancerSurvivor,Year
count,401958,401958,400997,393267.000000,394029.000000,394851,401276,397264.000000,392161,399875,...,393701,380227.000000,367010.000000,360601.000000,375183,349091,376216,345526,400775,401958.0
unique,53,2,5,NaN,NaN,4,2,NaN,4,2,...,13,NaN,NaN,NaN,2,2,2,2,2,NaN
top,Minnesota,Female,Very good,NaN,NaN,Within past year (anytime less than 12 months ...,Yes,NaN,None of them,No,...,Age 65 to 69,NaN,NaN,NaN,Yes,No,Yes,No,No,NaN
freq,15835,218016,138139,NaN,NaN,311146,305883,NaN,209239,377918,...,41570,NaN,NaN,NaN,191565,232101,197197,205331,363989,NaN
mean,NaN,NaN,NaN,3.457595,3.916334,NaN,NaN,7.097099,NaN,NaN,...,NaN,1.701243,82.320386,28.306313,NaN,NaN,NaN,NaN,NaN,2020.0
std,NaN,NaN,NaN,8.081710,8.045309,NaN,NaN,1.468063,NaN,NaN,...,NaN,0.107235,20.994057,6.381649,NaN,NaN,NaN,NaN,NaN,0.0
min,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,1.000000,NaN,NaN,...,NaN,0.910000,22.680000,12.020000,NaN,NaN,NaN,NaN,NaN,2020.0
25%,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,6.000000,NaN,NaN,...,NaN,1.630000,68.040000,23.990000,NaN,NaN,NaN,NaN,NaN,2020.0
50%,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,7.000000,NaN,NaN,...,NaN,1.700000,79.380000,27.320000,NaN,NaN,NaN,NaN,NaN,2020.0
75%,NaN,NaN,NaN,2.000000,3.000000,NaN,NaN,8.000000,NaN,NaN,...,NaN,1.780000,92.990000,31.380000,NaN,NaN,NaN,NaN,NaN,2020.0
max,NaN,NaN,NaN,30.000000,30.000000,NaN,NaN,24.000000,NaN,NaN,...,NaN,2.410000,290.300000,98.430000,NaN,NaN,NaN,NaN,NaN,2020.0

**Valores unicos**

In [ ]:
heart_2020_df.nunique().sort_values()

Year                            1
Sex                             2
HadSkinCancer                   2
PhysicalActivities              2
HadAsthma                       2
HadStroke                       2
HadAngina                       2
HadCOPD                         2
AlcoholDrinkers                 2
HIVTesting                      2
DifficultyDressingBathing       2
DifficultyErrands               2
DifficultyWalking               2
HadArthritis                    2
HadKidneyDisease                2
HadHeartAttack                  2
CancerSurvivor                  2
PneumoVaxEver                   2
FluVaxLast12                    2
HadDepressiveDisorder           2
ECigaretteUsage                 3
HadDiabetes                     4
SmokerStatus                    4
RemovedTeeth                    4
LastCheckupTime                 4
GeneralHealth                   5
RaceEthnicityCategory           5
TypeOfCancer                    6
AgeCategory                    13
SleepHours                     24
PhysicalHealthDays             31
MentalHealthDays               31
State                          53
HeightInMeters                110
WeightInKilograms             553
BMI                          3769
dtype: int64

In [ ]:
# Variables categoricas
heart_2020_df.select_dtypes(include='object').columns

Index(['State', 'Sex', 'GeneralHealth', 'LastCheckupTime',
       'PhysicalActivities', 'RemovedTeeth', 'HadHeartAttack', 'HadAngina',
       'HadStroke', 'HadAsthma', 'HadSkinCancer', 'TypeOfCancer', 'HadCOPD',
       'HadDepressiveDisorder', 'HadKidneyDisease', 'HadArthritis',
       'HadDiabetes', 'DifficultyWalking', 'DifficultyDressingBathing',
       'DifficultyErrands', 'SmokerStatus', 'ECigaretteUsage',
       'RaceEthnicityCategory', 'AgeCategory', 'AlcoholDrinkers', 'HIVTesting',
       'FluVaxLast12', 'PneumoVaxEver', 'CancerSurvivor'],
      dtype='object')

In [ ]:
# Variables numericas
heart_2020_df.select_dtypes(exclude='object').columns

Index(['PhysicalHealthDays', 'MentalHealthDays', 'SleepHours',
       'HeightInMeters', 'WeightInKilograms', 'BMI', 'Year'],
      dtype='object')

# **Valores faltantes**

In [ ]:
# Porcentaje de valores faltantes
missing = heart_2020_df.isnull().mean() * 100
missing.sort_values(ascending=False).head(20)

TypeOfCancer                 97.764194
ECigaretteUsage              87.395200
PneumoVaxEver                14.039278
HIVTesting                   13.152369
BMI                          10.288886
WeightInKilograms             8.694441
AlcoholDrinkers               6.661144
FluVaxLast12                  6.404152
HeightInMeters                5.406286
SmokerStatus                  5.249305
DifficultyErrands             4.505197
DifficultyWalking             4.169341
DifficultyDressingBathing     4.128292
RemovedTeeth                  2.437319
RaceEthnicityCategory         2.236055
PhysicalHealthDays            2.162166
AgeCategory                   2.054195
MentalHealthDays              1.972594
LastCheckupTime               1.768095
SleepHours                    1.167784
dtype: float64

In [ ]:
# Tabla ordenada
missing_table = missing.reset_index()
missing_table.columns = ['Variable', 'Porcentaje_NaN']
missing_table = missing_table.sort_values('Porcentaje_NaN', ascending=False)
missing_table

                     Variable  Porcentaje_NaN
14               TypeOfCancer       97.764194
24            ECigaretteUsage       87.395200
33              PneumoVaxEver       14.039278
31                 HIVTesting       13.152369
29                        BMI       10.288886
28          WeightInKilograms        8.694441
30            AlcoholDrinkers        6.661144
32               FluVaxLast12        6.404152
27             HeightInMeters        5.406286
23               SmokerStatus        5.249305
22          DifficultyErrands        4.505197
20          DifficultyWalking        4.169341
21  DifficultyDressingBathing        4.128292
8                RemovedTeeth        2.437319
25      RaceEthnicityCategory        2.236055
3          PhysicalHealthDays        2.162166
26                AgeCategory        2.054195
4            MentalHealthDays        1.972594
5             LastCheckupTime        1.768095
7                  SleepHours        1.167784
10                  HadAngina        0.821479
16      HadDepressiveDisorder        0.572945
17           HadKidneyDisease        0.523189
9              HadHeartAttack        0.518213
15                    HadCOPD        0.486369
18               HadArthritis        0.377154
12                  HadAsthma        0.340085
13              HadSkinCancer        0.317197
11                  HadStroke        0.295056
34             CancerSurvivor        0.294309
2               GeneralHealth        0.239080
19                HadDiabetes        0.202509
6          PhysicalActivities        0.169669
1                         Sex        0.000000
0                       State        0.000000
35                       Year        0.000000

## **Limpieza de variables mayores a 40% de NaN**

In [ ]:
# Columnas que se mantienen
columns_to_keep = missing[missing <= 40].index
columns_to_keep

Index(['State', 'Sex', 'GeneralHealth', 'PhysicalHealthDays',
       'MentalHealthDays', 'LastCheckupTime', 'PhysicalActivities',
       'SleepHours', 'RemovedTeeth', 'HadHeartAttack', 'HadAngina',
       'HadStroke', 'HadAsthma', 'HadSkinCancer', 'HadCOPD',
       'HadDepressiveDisorder', 'HadKidneyDisease', 'HadArthritis',
       'HadDiabetes', 'DifficultyWalking', 'DifficultyDressingBathing',
       'DifficultyErrands', 'SmokerStatus', 'RaceEthnicityCategory',
       'AgeCategory', 'HeightInMeters', 'WeightInKilograms', 'BMI',
       'AlcoholDrinkers', 'HIVTesting', 'FluVaxLast12', 'PneumoVaxEver',
       'CancerSurvivor', 'Year'],
      dtype='object')

In [ ]:
heart_clean = heart_2020_df[columns_to_keep]
heart_clean.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,AgeCategory,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,CancerSurvivor,Year
0,Alabama,Female,Very good,3.0,30.0,5 or more years ago,Yes,5.0,"6 or more, but not all",No,...,Age 55 to 59,1.70,48.08,16.60,No,Yes,No,No,Yes,2020
1,Alabama,Female,Good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,1 to 5,No,...,Age 65 to 69,1.63,77.11,29.18,NaN,NaN,NaN,NaN,No,2020
2,Alabama,Female,Good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,NaN,No,...,Age 65 to 69,1.73,NaN,NaN,No,No,Yes,No,Yes,2020
3,Alabama,Female,Excellent,0.0,0.0,Within past 2 years (1 year but less than 2 ye...,No,6.0,1 to 5,No,...,Age 80 or older,NaN,NaN,NaN,No,No,No,No,No,2020
4,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,None of them,No,...,Age 80 or older,1.68,57.15,20.34,No,NaN,Yes,Yes,No,2020

In [ ]:
# Resultado
print(f"Columnas originales: {heart_2020_df.shape[1]}")
print(f"Columnas después de limpieza: {heart_clean.shape[1]}")

Columnas originales: 36
Columnas después de limpieza: 34

In [ ]:
# Columnas eliminadas
columns_removed = missing[missing > 40].index
print("\nColumnas eliminadas por exceso de NaN (>40%):")
print(columns_removed.tolist())

Columnas eliminadas por exceso de NaN (>40%):
['TypeOfCancer', 'ECigaretteUsage']

# **Análisis de consistencia de variables**

## **Variables clave para el estudio**

In [ ]:
key_vars = ['HadHeartAttack','BMI','Sex','AgeCategory','SmokerStatus','RaceEthnicityCategory']

In [ ]:
# Copia del dataframe original
df_clean = heart_clean.copy()

### **Variable HadHeartAttack (Porcentaje de valores NaN -> 0.52%)**

In [ ]:
print("Valores faltantes antes de limpieza (HadHeartAttack):", df_clean['HadHeartAttack'].isna().sum())

Valores faltantes antes de limpieza (HadHeartAttack): 2083

In [ ]:
# Eliminar filas donde HadHeartAttack está vacío
df_clean = df_clean.dropna(subset=['HadHeartAttack'])

In [ ]:
df_clean['HadHeartAttack'].value_counts()

HadHeartAttack
No     377918
Yes     21957
Name: count, dtype: int64

In [ ]:
print(f"Cantidad de valores nulos en 'HadHeartAttack': {df_clean['HadHeartAttack'].isnull().sum()}")

Cantidad de valores nulos en 'HadHeartAttack': 0

### **Variable BMI (Porcentaje de valores NaN -> 10.29%)**

In [ ]:
print("Valores faltantes antes de imputación (BMI):", df_clean['BMI'].isna().sum())

Valores faltantes antes de imputación (BMI): 40912

In [ ]:
# Aplicamos la imputación con la mediana
bmi_median = df_clean['BMI'].median()
df_clean['BMI'].fillna(bmi_median, inplace=True)

/tmp/ipython-input-969017341.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['BMI'].fillna(bmi_median, inplace=True)

In [ ]:
# Verificamos nuevamente los valores faltantes
print("Valores faltantes después de imputación (BMI):", df_clean['BMI'].isna().sum())
print("Mediana utilizada para imputación:", round(bmi_median, 2))

Valores faltantes después de imputación (BMI): 0
Mediana utilizada para imputación: 27.32

### **Variable Sex (Porcentaje de valores NaN -> 0%)**

### **Variable AgeCategory (Porcentaje de valores NaN -> 2.05%)**

In [ ]:
# Mostramos cuántos valores faltantes hay antes de la imputación
print("Valores faltantes antes de imputación:")
print(df_clean['AgeCategory'].isna().sum())

Valores faltantes antes de imputación:
8036

In [ ]:
# Aplicamos imputación con la moda (valor más frecuente)
for col in ['AgeCategory']:
    mode_val = df_clean[col].mode()[0]
    df_clean[col].fillna(mode_val, inplace=True)
    print(f"→ Variable '{col}' imputada con la moda: '{mode_val}'")

→ Variable 'AgeCategory' imputada con la moda: 'Age 65 to 69'

/tmp/ipython-input-3354019741.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean[col].fillna(mode_val, inplace=True)

In [ ]:
df_clean['AgeCategory'].info()

<class 'pandas.core.series.Series'>
Index: 399875 entries, 0 to 401957
Series name: AgeCategory
Non-Null Count   Dtype
--------------   -----
399875 non-null  object
dtypes: object(1)
memory usage: 6.1+ MB

In [ ]:
# Verificamos nuevamente los valores faltantes después de imputar
print("\nValores faltantes después de imputación:")
print(df_clean[['AgeCategory']].isna().sum())

Valores faltantes después de imputación:
AgeCategory    0
dtype: int64

In [ ]:
# Verificar que ya no haya valores faltantes en las variables clave
print(df_clean[['HadHeartAttack', 'Sex', 'BMI', 'SmokerStatus', 'RaceEthnicityCategory', 'AgeCategory']].isnull().mean() * 100)

HadHeartAttack           0.000000
Sex                      0.000000
BMI                      0.000000
SmokerStatus             5.207627
RaceEthnicityCategory    2.196937
AgeCategory              0.000000
dtype: float64

### **Variable SmokerStatus (Porcentaje de valores NaN -> 5.25%)**

In [ ]:
# Mostramos cuántos valores faltantes hay antes de la imputación
print("Valores faltantes antes de imputación:")
print(df_clean['SmokerStatus'].isna().sum())

Valores faltantes antes de imputación:
20824

In [ ]:
# Aplicamos imputación con la moda (valor más frecuente)
for col in ['SmokerStatus']:
    mode_val = df_clean[col].mode()[0]
    df_clean[col].fillna(mode_val, inplace=True)
    print(f"→ Variable '{col}' imputada con la moda: '{mode_val}'")

→ Variable 'SmokerStatus' imputada con la moda: 'Never smoked'

/tmp/ipython-input-3349073259.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean[col].fillna(mode_val, inplace=True)

In [ ]:
df_clean['SmokerStatus'].value_counts()

SmokerStatus
Never smoked                             244339
Former smoker                            103319
Current smoker - now smokes every day     37962
Current smoker - now smokes some days     14255
Name: count, dtype: int64

In [ ]:
# Verificamos nuevamente los valores faltantes después de imputar
print("\nValores faltantes después de imputación:")
print(df_clean[['SmokerStatus']].isna().sum())

Valores faltantes después de imputación:
SmokerStatus    0
dtype: int64

### **Variable RaceEthnicityCategory (Porcentaje de valores NaN -> 2.24%)**

In [ ]:
# Mostramos cuántos valores faltantes hay antes de la imputación
print("Valores faltantes antes de imputación:")
print(df_clean['RaceEthnicityCategory'].isna().sum())

Valores faltantes antes de imputación:
8785

In [ ]:
# Aplicamos imputación con la moda (valor más frecuente)
for col in ['RaceEthnicityCategory']:
    mode_val = df_clean[col].mode()[0]
    df_clean[col].fillna(mode_val, inplace=True)
    print(f"→ Variable '{col}' imputada con la moda: '{mode_val}'")

→ Variable 'RaceEthnicityCategory' imputada con la moda: 'White only, Non-Hispanic'

/tmp/ipython-input-607064637.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean[col].fillna(mode_val, inplace=True)

In [ ]:
df_clean['RaceEthnicityCategory'].value_counts()

RaceEthnicityCategory
White only, Non-Hispanic         303521
Hispanic                          36085
Black only, Non-Hispanic          29918
Other race only, Non-Hispanic     22086
Multiracial, Non-Hispanic          8265
Name: count, dtype: int64

In [ ]:
# Verificamos nuevamente los valores faltantes después de imputar
print("\nValores faltantes después de imputación:")
print(df_clean[['SmokerStatus']].isna().sum())

Valores faltantes después de imputación:
SmokerStatus    0
dtype: int64

## **Imputación de variables restantes**

### **Variables completas**
*   **Variable State (Porcentaje de valores NaN -> 0%)**
*   **Variable Year (Porcentaje de valores NaN -> 0%)**

### **Imputación de variables numéricas**

*   **Variable SleepHours (Porcentaje de valores NaN -> 1.17%)**
*   **Variable PhysicalHealthDays (Porcentaje de valores NaN -> 2.16%)**
*   **Variable MentalHealthDays (Porcentaje de valores NaN -> 1.97%)**
*   **Variable HeightInMeters (Porcentaje de valores NaN -> 5.41%)**
*   **Variable WeightInKilograms (Porcentaje de valores NaN -> 8.69%)**

In [ ]:
# Imputación de variables numéricas
numeric_cols = ['SleepHours', 'PhysicalHealthDays', 'MentalHealthDays', 'HeightInMeters', 'WeightInKilograms']

In [ ]:
for col in numeric_cols:
    median_val = df_clean[col].median()
    df_clean[col].fillna(median_val, inplace=True)
    print(f"{col}: valores imputados con mediana {median_val:.2f}")

SleepHours: valores imputados con mediana 7.00
PhysicalHealthDays: valores imputados con mediana 0.00
MentalHealthDays: valores imputados con mediana 0.00
HeightInMeters: valores imputados con mediana 1.70
WeightInKilograms: valores imputados con mediana 79.38

/tmp/ipython-input-1228349538.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean[col].fillna(median_val, inplace=True)

In [ ]:
# Verificar que ya no haya valores faltantes en las variables clave
print(df_clean[['SleepHours', 'PhysicalHealthDays', 'MentalHealthDays', 'HeightInMeters', 'WeightInKilograms']].isnull().mean() * 100)

SleepHours            0.0
PhysicalHealthDays    0.0
MentalHealthDays      0.0
HeightInMeters        0.0
WeightInKilograms     0.0
dtype: float64

### **Imputación de variables categóricas**

*   **Variable GeneralHealth (Porcentaje de valores NaN -> 0.24%)**
*   **Variable LastCheckupTime (Porcentaje de valores NaN -> 1.77%)**
*   **Variable RemovedTeeth (Porcentaje de valores NaN -> 2.44%)**

In [ ]:
# Imputación de variables categóricas ordinales
ordinal_cols = ['GeneralHealth', 'LastCheckupTime', 'RemovedTeeth']

In [ ]:
for col in ordinal_cols:
    mode_val = df_clean[col].mode()[0]
    df_clean[col].fillna(mode_val, inplace=True)
    print(f"{col}: valores imputados con moda '{mode_val}'")

GeneralHealth: valores imputados con moda 'Very good'
LastCheckupTime: valores imputados con moda 'Within past year (anytime less than 12 months ago)'
RemovedTeeth: valores imputados con moda 'None of them'

/tmp/ipython-input-333117031.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean[col].fillna(mode_val, inplace=True)

In [ ]:
# Verificar que ya no haya valores faltantes en las variables clave
print(df_clean[['GeneralHealth', 'LastCheckupTime', 'RemovedTeeth']].isnull().mean() * 100)

GeneralHealth      0.0
LastCheckupTime    0.0
RemovedTeeth       0.0
dtype: float64

### **Imputación de variables binarias**

*   **Variable PneumoVaxEver (Porcentaje de valores NaN -> 14.04%)**
*   **Variable HIVTesting (Porcentaje de valores NaN -> 13.15%)**
*   **Variable AlcoholDrinkers (Porcentaje de valores NaN -> 6.66%)**
*   **Variable FluVaxLast12 (Porcentaje de valores NaN -> 6.40%)**
*   **Variable DifficultyErrands (Porcentaje de valores NaN -> 4.51%)**
*   **Variable DifficultyWalking (Porcentaje de valores NaN -> 4.17%)**
*   **Variable DifficultyDressingBathing (Porcentaje de valores NaN -> 4.13%)**
*   **Variable HadAngina (Porcentaje de valores NaN -> 0.82%)**
*   **Variable HadDepressiveDisorder (Porcentaje de valores NaN -> 0.57%)**
*   **Variable HadKidneyDisease (Porcentaje de valores NaN -> 0.52%)**
*   **Variable HadCOPD (Porcentaje de valores NaN -> 0.49%)**
*   **Variable HadArthritis (Porcentaje de valores NaN -> 0.38)**
*   **Variable HadAsthma (Porcentaje de valores NaN -> 0.34%)**
*   **Variable HadSkinCancer (Porcentaje de valores NaN -> 0.32%)**
*   **Variable HadStroke (Porcentaje de valores NaN -> 0.30%)**
*   **Variable CancerSurvivor (Porcentaje de valores NaN -> 0.29%)**
*   **Variable HadDiabetes (Porcentaje de valores NaN -> 0.20%)**
*   **Variable PhysicalActivities (Porcentaje de valores NaN -> 0.17%)**

In [ ]:
# Imputación de variables binarias Sí/No
binary_cols = ['PneumoVaxEver', 'HIVTesting', 'AlcoholDrinkers', 'FluVaxLast12', 'DifficultyErrands', 'DifficultyWalking',
               'DifficultyDressingBathing','HadAngina', 'HadDepressiveDisorder','HadKidneyDisease','HadCOPD','HadArthritis','HadAsthma','HadSkinCancer',
               'HadStroke','CancerSurvivor','HadDiabetes','PhysicalActivities']

In [ ]:
for col in binary_cols:
    mode_val = df_clean[col].mode()[0]
    df_clean[col].fillna(mode_val, inplace=True)
    print(f"{col}: valores imputados con moda '{mode_val}'")

/tmp/ipython-input-1213171526.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean[col].fillna(mode_val, inplace=True)

PneumoVaxEver: valores imputados con moda 'No'
HIVTesting: valores imputados con moda 'No'
AlcoholDrinkers: valores imputados con moda 'Yes'
FluVaxLast12: valores imputados con moda 'Yes'
DifficultyErrands: valores imputados con moda 'No'
DifficultyWalking: valores imputados con moda 'No'
DifficultyDressingBathing: valores imputados con moda 'No'
HadAngina: valores imputados con moda 'No'
HadDepressiveDisorder: valores imputados con moda 'No'
HadKidneyDisease: valores imputados con moda 'No'
HadCOPD: valores imputados con moda 'No'
HadArthritis: valores imputados con moda 'No'
HadAsthma: valores imputados con moda 'No'
HadSkinCancer: valores imputados con moda 'No'
HadStroke: valores imputados con moda 'No'
CancerSurvivor: valores imputados con moda 'No'
HadDiabetes: valores imputados con moda 'No'
PhysicalActivities: valores imputados con moda 'Yes'

In [ ]:
# Verificar que ya no haya valores faltantes en las variables clave
print(df_clean[['PneumoVaxEver', 'HIVTesting', 'AlcoholDrinkers', 'FluVaxLast12', 'DifficultyErrands', 'DifficultyWalking',
               'DifficultyDressingBathing','HadAngina', 'HadDepressiveDisorder','HadKidneyDisease','HadCOPD','HadArthritis','HadAsthma','HadSkinCancer',
               'HadStroke','CancerSurvivor','HadDiabetes','PhysicalActivities','HadHeartAttack']].isnull().mean() * 100)

PneumoVaxEver                0.0
HIVTesting                   0.0
AlcoholDrinkers              0.0
FluVaxLast12                 0.0
DifficultyErrands            0.0
DifficultyWalking            0.0
DifficultyDressingBathing    0.0
HadAngina                    0.0
HadDepressiveDisorder        0.0
HadKidneyDisease             0.0
HadCOPD                      0.0
HadArthritis                 0.0
HadAsthma                    0.0
HadSkinCancer                0.0
HadStroke                    0.0
CancerSurvivor               0.0
HadDiabetes                  0.0
PhysicalActivities           0.0
HadHeartAttack               0.0
dtype: float64

## **Tratamiento de outliers (Valores extremos)**

In [ ]:
for var in ['BMI', 'SleepHours', 'HeightInMeters', 'WeightInKilograms']:
    Q1 = df_clean[var].quantile(0.25)
    Q3 = df_clean[var].quantile(0.75)
    IQR = Q3 - Q1
    df_clean = df_clean[(df_clean[var] >= Q1 - 1.5 * IQR) & (df_clean[var] <= Q3 + 1.5 * IQR)]

In [ ]:
print("\nValidación del DataFrame limpio:")
print(df_clean.info())

Validación del DataFrame limpio:
<class 'pandas.core.frame.DataFrame'>
Index: 370971 entries, 0 to 401957
Data columns (total 34 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   State                      370971 non-null  object
 1   Sex                        370971 non-null  object
 2   GeneralHealth              370971 non-null  object
 3   PhysicalHealthDays         370971 non-null  float64
 4   MentalHealthDays           370971 non-null  float64
 5   LastCheckupTime            370971 non-null  object
 6   PhysicalActivities         370971 non-null  object
 7   SleepHours                 370971 non-null  float64
 8   RemovedTeeth               370971 non-null  object
 9   HadHeartAttack             370971 non-null  object
 10  HadAngina                  370971 non-null  object
 11  HadStroke                  370971 non-null  object
 12  HadAsthma                  370971 non-null  object
 13  HadSkinCancer              370971 non-null  object
 14  HadCOPD                    370971 non-null  object
 15  HadDepressiveDisorder      370971 non-null  object
 16  HadKidneyDisease           370971 non-null  object
 17  HadArthritis               370971 non-null  object
 18  HadDiabetes                370971 non-null  object
 19  DifficultyWalking          370971 non-null  object
 20  DifficultyDressingBathing  370971 non-null  object
 21  DifficultyErrands          370971 non-null  object
 22  SmokerStatus               370971 non-null  object
 23  RaceEthnicityCategory      370971 non-null  object
 24  AgeCategory                370971 non-null  object
 25  HeightInMeters             370971 non-null  float64
 26  WeightInKilograms          370971 non-null  float64
 27  BMI                        370971 non-null  float64
 28  AlcoholDrinkers            370971 non-null  object
 29  HIVTesting                 370971 non-null  object
 30  FluVaxLast12               370971 non-null  object
 31  PneumoVaxEver              370971 non-null  object
 32  CancerSurvivor             370971 non-null  object
 33  Year                       370971 non-null  int64
dtypes: float64(6), int64(1), object(27)
memory usage: 99.1+ MB
None

In [ ]:
df_clean.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,AgeCategory,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,CancerSurvivor,Year
0,Alabama,Female,Very good,3.0,30.0,5 or more years ago,Yes,5.0,"6 or more, but not all",No,...,Age 55 to 59,1.70,48.08,16.60,No,Yes,No,No,Yes,2020
1,Alabama,Female,Good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,1 to 5,No,...,Age 65 to 69,1.63,77.11,29.18,Yes,No,Yes,No,No,2020
2,Alabama,Female,Good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,None of them,No,...,Age 65 to 69,1.73,79.38,27.32,No,No,Yes,No,Yes,2020
3,Alabama,Female,Excellent,0.0,0.0,Within past 2 years (1 year but less than 2 ye...,No,6.0,1 to 5,No,...,Age 80 or older,1.70,79.38,27.32,No,No,No,No,No,2020
4,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,None of them,No,...,Age 80 or older,1.68,57.15,20.34,No,No,Yes,Yes,No,2020

## **Guardar archivo csv - Para Análisis Descriptivo**

In [ ]:
# Ruta a tu carpeta del proyecto
BASE = Path('/content/drive/MyDrive/Proyecto_de_tesis/datos_2020')
CLEAN = BASE / 'data' / 'cleaned'

In [ ]:
# Guardar el archivo limpio
output_path = CLEAN / 'heart_data_clean_2020_descriptive.csv'
df_clean.to_csv(output_path, index=False)

## **Normalización y codificación binaria**

In [ ]:
# Copia de base de datos para modelo predictivo
df_clean_pred = df_clean.copy()

In [ ]:
binary_vars = ['PneumoVaxEver', 'HIVTesting', 'AlcoholDrinkers', 'FluVaxLast12', 'DifficultyErrands', 'DifficultyWalking',
               'DifficultyDressingBathing','HadAngina', 'HadDepressiveDisorder','HadKidneyDisease','HadCOPD','HadArthritis','HadAsthma','HadSkinCancer',
               'HadStroke','CancerSurvivor','HadDiabetes','PhysicalActivities','HadHeartAttack']

In [ ]:
for col in binary_vars:
    df_clean_pred[col] = df_clean_pred[col].replace({'Yes': 1, 'No': 0})

/tmp/ipython-input-421723925.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_clean_pred[col] = df_clean_pred[col].replace({'Yes': 1, 'No': 0})

In [ ]:
def describe_df(df: pd.DataFrame):
    print(f"The dataset contains {df.shape[1]} columns and {len(df)} rows")

    for col in df.columns:
        col_dtype = df[col].dtype

        print(f"\nColumn: {col} ({col_dtype})")
        if col_dtype == 'object':
            print(f"--- Percentage of NaNs: {df[col].isna().sum() / len(df[col]) * 100}")
            print(f"--- Unique values:\n {df[col].unique()}")
        else:
            print(f"--- Summary statistics:\n {df[col].describe()}")

In [ ]:
describe_df(df_clean_pred)

The dataset contains 34 columns and 370971 rows

Column: State (object)
--- Percentage of NaNs: 0.0
--- Unique values:
 ['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'District of Columbia' 'Florida' 'Georgia'
 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas' 'Kentucky'
 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan' 'Minnesota'
 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada' 'New Hampshire'
 'New Jersey' 'New Mexico' 'New York' 'North Carolina' 'North Dakota'
 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Rhode Island' 'South Carolina'
 'South Dakota' 'Tennessee' 'Texas' 'Utah' 'Vermont' 'Virginia'
 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming' 'Guam' 'Puerto Rico']

Column: Sex (object)
--- Percentage of NaNs: 0.0
--- Unique values:
 ['Female' 'Male']

Column: GeneralHealth (object)
--- Percentage of NaNs: 0.0
--- Unique values:
 ['Very good' 'Good' 'Excellent' 'Fair' 'Poor']

Column: PhysicalHealthDays (float64)
--- Summary statistics:
 count    370971.000000
mean          3.128603
std           7.692423
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max          30.000000
Name: PhysicalHealthDays, dtype: float64

Column: MentalHealthDays (float64)
--- Summary statistics:
 count    370971.000000
mean          3.664815
std           7.777746
min           0.000000
25%           0.000000
50%           0.000000
75%           3.000000
max          30.000000
Name: MentalHealthDays, dtype: float64

Column: LastCheckupTime (object)
--- Percentage of NaNs: 0.0
--- Unique values:
 ['5 or more years ago'
 'Within past year (anytime less than 12 months ago)'
 'Within past 2 years (1 year but less than 2 years ago)'
 'Within past 5 years (2 years but less than 5 years ago)']

Column: PhysicalActivities (int64)
--- Summary statistics:
 count    370971.000000
mean          0.775333
std           0.417364
min           0.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: PhysicalActivities, dtype: float64

Column: SleepHours (float64)
--- Summary statistics:
 count    370971.000000
mean          7.070221
std           1.232463
min           3.000000
25%           6.000000
50%           7.000000
75%           8.000000
max          11.000000
Name: SleepHours, dtype: float64

Column: RemovedTeeth (object)
--- Percentage of NaNs: 0.0
--- Unique values:
 ['6 or more, but not all' '1 to 5' 'None of them' 'All']

Column: HadHeartAttack (int64)
--- Summary statistics:
 count    370971.000000
mean          0.053136
std           0.224305
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: HadHeartAttack, dtype: float64

Column: HadAngina (int64)
--- Summary statistics:
 count    370971.000000
mean          0.053875
std           0.225771
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: HadAngina, dtype: float64

Column: HadStroke (int64)
--- Summary statistics:
 count    370971.000000
mean          0.037267
std           0.189416
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: HadStroke, dtype: float64

Column: HadAsthma (int64)
--- Summary statistics:
 count    370971.000000
mean          0.128665
std           0.334829
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: HadAsthma, dtype: float64

Column: HadSkinCancer (int64)
--- Summary statistics:
 count    370971.000000
mean          0.092401
std           0.289591
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: HadSkinCancer, dtype: float64

Column: HadCOPD (int64)
--- Summary statistics:
 count    370971.000000
mean          0.073585
std           0.261095
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: HadCOPD, dtype: float64

Column: HadDepressiveDisorder (int64)
--- Summary statistics:
 count    370971.000000
mean          0.300501
std           0.458476
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: HadDepressiveDisorder, dtype: float64

Column: HadKidneyDisease (int64)
--- Summary statistics:
 count    370971.000000
mean          0.179626
std           0.383876
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: HadKidneyDisease, dtype: float64

Column: HadArthritis (int64)
--- Summary statistics:
 count    370971.000000
mean          0.035124
std           0.184094
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: HadArthritis, dtype: float64

Column: HadDiabetes (object)
--- Percentage of NaNs: 0.0
--- Unique values:
 [1 0 'No, pre-diabetes or borderline diabetes'
 'Yes, but only during pregnancy (female)']

Column: DifficultyWalking (int64)
--- Summary statistics:
 count    370971.000000
mean          0.128064
std           0.334161
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: DifficultyWalking, dtype: float64

Column: DifficultyDressingBathing (int64)
--- Summary statistics:
 count    370971.000000
mean          0.028994
std           0.167790
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: DifficultyDressingBathing, dtype: float64

Column: DifficultyErrands (int64)
--- Summary statistics:
 count    370971.000000
mean          0.058964
std           0.235558
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: DifficultyErrands, dtype: float64

Column: SmokerStatus (object)
--- Percentage of NaNs: 0.0
--- Unique values:
 ['Current smoker - now smokes every day' 'Never smoked' 'Former smoker'
 'Current smoker - now smokes some days']

Column: RaceEthnicityCategory (object)
--- Percentage of NaNs: 0.0
--- Unique values:
 ['White only, Non-Hispanic' 'Black only, Non-Hispanic'
 'Other race only, Non-Hispanic' 'Multiracial, Non-Hispanic' 'Hispanic']

Column: AgeCategory (object)
--- Percentage of NaNs: 0.0
--- Unique values:
 ['Age 55 to 59' 'Age 65 to 69' 'Age 80 or older' 'Age 75 to 79'
 'Age 40 to 44' 'Age 70 to 74' 'Age 60 to 64' 'Age 50 to 54'
 'Age 45 to 49' 'Age 18 to 24' 'Age 35 to 39' 'Age 25 to 29'
 'Age 30 to 34']

Column: HeightInMeters (float64)
--- Summary statistics:
 count    370971.000000
mean          1.699832
std           0.099950
min           1.420000
25%           1.630000
50%           1.700000
75%           1.780000
max           2.000000
Name: HeightInMeters, dtype: float64

Column: WeightInKilograms (float64)
--- Summary statistics:
 count    370971.000000
mean         79.277161
std          15.991604
min          34.470000
25%          68.040000
50%          79.380000
75%          90.260000
max         124.280000
Name: WeightInKilograms, dtype: float64

Column: BMI (float64)
--- Summary statistics:
 count    370971.000000
mean         27.296407
std           4.567155
min          14.650000
25%          24.210000
50%          27.320000
75%          29.950000
max          40.570000
Name: BMI, dtype: float64

Column: AlcoholDrinkers (int64)
--- Summary statistics:
 count    370971.000000
mean          0.551208
std           0.497372
min           0.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: AlcoholDrinkers, dtype: float64

Column: HIVTesting (int64)
--- Summary statistics:
 count    370971.000000
mean          0.287160
std           0.452437
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: HIVTesting, dtype: float64

Column: FluVaxLast12 (int64)
--- Summary statistics:
 count    370971.000000
mean          0.557138
std           0.496725
min           0.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: FluVaxLast12, dtype: float64

Column: PneumoVaxEver (int64)
--- Summary statistics:
 count    370971.000000
mean          0.347539
std           0.476189
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: PneumoVaxEver, dtype: float64

Column: CancerSurvivor (int64)
--- Summary statistics:
 count    370971.00000
mean          0.09150
std           0.28832
min           0.00000
25%           0.00000
50%           0.00000
75%           0.00000
max           1.00000
Name: CancerSurvivor, dtype: float64

Column: Year (int64)
--- Summary statistics:
 count    370971.0
mean       2020.0
std           0.0
min        2020.0
25%        2020.0
50%        2020.0
75%        2020.0
max        2020.0
Name: Year, dtype: float64

In [ ]:
df_clean_pred.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,AgeCategory,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,CancerSurvivor,Year
0,Alabama,Female,Very good,3.0,30.0,5 or more years ago,1,5.0,"6 or more, but not all",0,...,Age 55 to 59,1.70,48.08,16.60,0,1,0,0,1,2020
1,Alabama,Female,Good,0.0,0.0,Within past year (anytime less than 12 months ...,1,7.0,1 to 5,0,...,Age 65 to 69,1.63,77.11,29.18,1,0,1,0,0,2020
2,Alabama,Female,Good,0.0,0.0,Within past year (anytime less than 12 months ...,1,7.0,None of them,0,...,Age 65 to 69,1.73,79.38,27.32,0,0,1,0,1,2020
3,Alabama,Female,Excellent,0.0,0.0,Within past 2 years (1 year but less than 2 ye...,0,6.0,1 to 5,0,...,Age 80 or older,1.70,79.38,27.32,0,0,0,0,0,2020
4,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,1,7.0,None of them,0,...,Age 80 or older,1.68,57.15,20.34,0,0,1,1,0,2020

## **Guardar archivo csv - Para Modelo Predictivo**

In [ ]:
# Ruta a tu carpeta del proyecto
BASE = Path('/content/drive/MyDrive/Proyecto_de_tesis/datos_2020')
CLEAN = BASE / 'data' / 'cleaned'

In [ ]:
# Guardar el archivo limpio
output_path = CLEAN / 'heart_data_clean_2020_predictive.csv'
df_clean_pred.to_csv(output_path, index=False)